[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.zip"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
